### ISSUE TITLE
Renaming this Repository

### ISSUE THREAD

**Issue by BjarneBitscrambler** [BjarneBitscrambler/OrientationSensorFusion-ESP#2]
I'm about to post the sensor-fusion code that I've ported to the ESP32  platform. Before I do, I'm renaming this repository.
@tedenda and @DanielG86 - if you have bookmarks to this repository you may have to update them...

**Comment by DanielG86** [comment]
No worries.

**Comment by BjarneBitscrambler** [comment]
Rename done, and the current working code has been pushed.  I'll spend a couple days testing and tweaking the files - let me know of any problems you notice if you happen to try out the code.

**Comment by tedenda** [comment]
I try it tomorrow!
